name             'backslasher-python'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures backslasher-python'
long_description 'Installs/Configures backslasher-python'
version          '0.1.0'
